---
# AWS Configuration
aws_region: eu-north-1
instance_type: t3.micro
ami_id: ami-0705384c0b33c194c  # Ubuntu 22.04 LTS eu-north-1

# Project Configuration
project_name: devops-automation
key_name: devops-automation-key
security_group_name: devops-automation-sg
instance_name: devops-automation-server

# Application Configuration
app_port: 80
app_directory: /home/ubuntu/app
git_repo: "{{ lookup('env', 'GITHUB_REPOSITORY') }}"

# Docker Configuration
docker_image_name: devops-app
container_name: devops-app