---
plugin: aws_ec2
regions:
  - eu-north-1
filters:
  tag:Name: devops-automation-server
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address