all:
  hosts:
    devops-server:
      ansible_host: "{{ lookup('env', 'EC2_IP') }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/devops-automation-key
      ansible_python_interpreter: /usr/bin/python3